# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: rapid7-insightappsec@1
      inputs:
        apiConnection: 'Pete - IAS - Azure devops'
        application: '6ebdb7d8-1447-43a5-bb1e-d2d266e75708'
        scanConfig: 'DVWA'
        generateFindingsReport: true
        hasTimeout: false
        hasScanGating: true
        vulnQuery: 'vulnerability.severity=''HIGH'''
        publishPipelineArtifacts: true
        artifactPerReport: true