# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: rapid7-insightappsec@1
      inputs:
        apiConnection: 'Pete - IAS - Azure devops'
        application: '9bc9e867-5512-4bf8-bd36-d3a9c31bb78f'
        scanConfig: 'Azure Test'
        generateFindingsReport: true
        hasTimeout: false
        hasScanGating: true
        vulnQuery: 'vulnerability.severity=''HIGH''OR''Medium'''
        publishPipelineArtifacts: true
        artifactPerReport: true