 name: IAS Scan
 on:
   push:
     branches: [ master ]
 jobs:
   scan:
     runs-on: ubuntu-latest
     steps:
       - id: my-scan
         uses: rapid7/insightappsec-scan-github-actions@v1.3.1
         with:
           region: "us2"
           api-key: ${{ secrets.IAS_API_KEY }}
           scan-config-id: "afb8674a-f911-4f3c-ac62-50e2d45d05f2"
           vuln-query: "vulnerability.severity = 'HIGH'"
       - name: Upload findings
         if: always()
         run: echo "${{ steps.my-scan.outputs.scan-findings }}"
