 name: Ias Scan
 on:
   push:
     branches: [ master ]
 jobs:
   scan:
     runs-on: ubuntu-latest
     steps:
       - id: my-scan
         uses: rapid7/insightappsec-scan-github-actions@v1.1.0
         with:
           region: "us"
           api-key: ${{ secrets.IAS_API_KEY }}
           scan-config-id: "6dd4636d-c8e4-44bc-b86b-97bfd733158a"
           vuln-query: "vulnerability.severity = 'HIGH'"
       - name: Upload findings
         if: always()
         run: echo "${{ steps.my-scan.outputs.scan-findings }}"
